/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LocalIdRouteImport } from './routes/local.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalIdRoute = LocalIdRouteImport.update({
  id: '/local/$id',
  path: '/local/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRoute
  '/sobre': typeof SobreRoute
  '/local/$id': typeof LocalIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRoute
  '/sobre': typeof SobreRoute
  '/local/$id': typeof LocalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof PainelRoute
  '/sobre': typeof SobreRoute
  '/local/$id': typeof LocalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin' | '/app' | '/entrar' | '/painel' | '/sobre' | '/local/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/app' | '/entrar' | '/painel' | '/sobre' | '/local/$id'
  id:
    | '__root__'
    | '/admin'
    | '/app'
    | '/entrar'
    | '/painel'
    | '/sobre'
    | '/local/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  EntrarRoute: typeof EntrarRoute
  PainelRoute: typeof PainelRoute
  SobreRoute: typeof SobreRoute
  LocalIdRoute: typeof LocalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$id': {
      id: '/local/$id'
      path: '/local/$id'
      fullPath: '/local/$id'
      preLoaderRoute: typeof LocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  EntrarRoute: EntrarRoute,
  PainelRoute: PainelRoute,
  SobreRoute: SobreRoute,
  LocalIdRoute: LocalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
